src/lib/data/aircraft.ts

Add several regional aircraft types common in Canada.

fix: add CRJ and DH8 aircraft

---

src/lib/components/map/Map.svelte
src/lib/utils/data/data.ts

fix: color future flights differently than other flights

---

docs/docs/features/add-flight.md
docs/docs/features/export.md
docs/docs/features/import.md
docs/docs/features/oauth.md
docs/docs/features/statistics.md
docs/docs/install/post-installation.md

Contains documentation updates that only apply to the next version of AirTrail.

docs: adding a flight

---

src/lib/components/map/Airports.svelte
src/lib/data/transitions.ts
src/lib/import/fr24.ts
src/lib/utils/csv.ts
src/routes/+layout.svelte

Also fixes a few smaller bugs and adds a few known airline transitions

fix: handle csv cells that span multiple lines

---

src/lib/data/README.md

fix: change IATA code of Chisinau International Airport

---

src/routes/api/flight/save/+server.ts

fix: allow entering flight times between 00:00 and 00:59

---

src/lib/components/form-fields/DateTimeField.svelte

fix: first weekday in datepicker is in accordance with browser

---

scripts/other/update-airports-data.cjs
src/lib/data/README.md
src/lib/data/transitions.ts

And correct ICAO "FLLS" to "FLKK".

fix: remove unused airport field "wiki" (saves ~1mb)

---

src/lib/server/utils/config.ts

fix: avoid lowercasing parsed env-var values

---

src/lib/components/modals/add-flight/FlightNumber.svelte

fix: flight number lookup

---

src/lib/db/queries.ts
src/lib/server/utils/flight.ts
src/lib/utils/data/data.ts
src/lib/utils/datetime/duration.ts
src/lib/utils/datetime/helpers.ts
src/lib/utils/datetime/parse.test.ts

fix: stop converting flight date timezone if no time has been set

---

src/lib/components/flight-filters/DateFilter.svelte
src/lib/components/form-fields/DateTimeField.svelte
src/lib/components/ui/calendar/calendar-cell.svelte
src/lib/components/ui/calendar/calendar-day.svelte
src/lib/components/ui/calendar/calendar-head-cell.svelte
src/lib/components/ui/calendar/calendar-heading.svelte
src/lib/components/ui/calendar/calendar-months.svelte
src/lib/components/ui/calendar/calendar-next-button.svelte
src/lib/components/ui/calendar/calendar-prev-button.svelte
src/lib/components/ui/calendar/calendar.svelte
src/lib/components/ui/calendar/index.ts
src/lib/components/ui/popover/popover-content.svelte

feat: enhance date picker with year and month selection

---

src/lib/components/modals/statistics/charts/PieChart.svelte
src/lib/components/modals/statistics/charts/PieCharts.svelte

Fix for #259 
I've also added a Title field on top to explain what the chart is

feat: add a PieChart for most specific aircraft flown

---

CONTRIBUTING.md

- add test user info (login and password)

docs: Improve contributing informations 

---

src/lib/import/jetlog.ts

fix(jetlog): if arrival time is before departure and no arrival_date is provided, assume next-day arrival

---

src/lib/components/modals/statistics/charts/PieCharts.svelte

Adds a "Top routes" PieChart to the stat page

feat: add a PieChart for most flown routes

---

src/lib/components/modals/add-flight/FlightNumber.svelte
src/lib/server/routes/flight.ts
src/lib/server/utils/flight-lookup/aerodatabox.ts

fix: handle timezone offset passed to flight lookup endpoint

---

src/lib/components/modals/statistics/charts/PieCharts.svelte

feat: Add a piechart for Top 5 most visited airports

---

src/lib/components/modals/statistics/StatisticsModal.svelte
src/lib/components/modals/statistics/charts/ChartDrillDown.svelte
src/lib/components/modals/statistics/charts/PieChart.svelte
src/lib/components/modals/statistics/charts/PieCharts.svelte
src/lib/stats/aggregations.ts

feat: introduce interactive pie charts with drill-down functionality in statistics

---

docs/content/docs/features/import.mdx
src/lib/components/modals/settings/pages/import-page/ImportPage.svelte
src/lib/components/modals/settings/pages/import-page/index.ts
src/lib/import/flighty.ts
src/lib/import/index.ts

Thanks to the helpful people in #199 who have provided their home-made scripts for the same purpose!

feat: Flighty import

---

src/lib/components/modals/edit-flight/EditFlightModal.svelte
src/lib/components/modals/settings/pages/import-page/index.ts
src/lib/import/airtrail.ts
src/lib/import/index.ts
src/lib/import/legacy-airtrail.ts
src/lib/server/routes/aircraft.ts
src/lib/server/routes/airline.ts
src/lib/server/routes/flight.ts
src/lib/server/utils/aircraft.ts
src/lib/server/utils/airline.ts
src/lib/utils/other.ts

Also fixes some small issues in the export file formats

feat: add legacy airtrail file importing

---

prisma/migrations/20250902115704_public_share_show_seat/migration.sql
prisma/schema.prisma
src/lib/components/modals/settings/pages/CreateShare.svelte
src/lib/components/modals/settings/pages/EditShare.svelte
src/lib/components/modals/settings/pages/ShareFormFields.svelte
src/lib/db/schema.d.ts
src/lib/db/types.ts
src/lib/server/utils/share.ts
src/lib/zod/share.ts

feat: add `showSeat` option to public shares

---

src/lib/components/modals/statistics/StatisticsModal.svelte
src/lib/components/modals/statistics/charts/PieCharts.svelte
src/lib/stats/aggregations.ts
src/routes/share/[slug]/+page.svelte

fix: seat data not showing in shared statistics
